name: Continuous Integration

on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Show Python version
        run: "python --version"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: jenk

      - name: Show directory
        run: 'pwd'

      - name: List files
        run: 'ls -al'

      - name: Install Dependencies
        run: 'python -m pip install -r requirements.txt'

      - name: Run Tests
        run: 'python -m unittest discover'

      - name: Display workflow link
        run: echo "Workflow link: ${{ github.run_url }}"
