name: Continuous Integration

on:
  push:
    branches:
      - main
      - jenk

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Update repository
      if: github.event_name == 'push' && (github.event_ref == 'refs/heads/main' || github.event_ref == 'refs/heads/jenks')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update project code [skip ci]"

        git push origin ${{ github.event_ref_name }}

    - name: Display workflow link
      run: echo "Workflow link: ${{ github.run_url }}"

