name: Continuous Integration

on:

  push:

    branches:

      - main

      - jenk

  workflow_dispatch:

  

jobs:

  my_first_job:

    runs-on: ubuntu-latest

 

    steps:

    

steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python my_script.py

 

    - name: Checkout code

      uses: actions/checkout@v3

      with:

        ref: jenk

 

    - name: Show directory

      run: 'pwd'

 

    - name: List files

      run: 'ls -al'

 

    - name: Install Dependencies

      run: 'mvn compile'

 

    - name: Build application

      run: 'mvn package -DskipTests'

 

    - name: Test application

      run: 'mvn test'

