name: Continuous Integration

on:

  push:

    branches:

      - main

      - jenk

  workflow_dispatch:

  

jobs:

  my_first_job:

    runs-on: ubuntu-latest

 steps:
 
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python my_script.py
